# This file contains information about the device associated with this repo
# This is a .properties file, but is also interpreted as a Makefile,
# so keep the syntax simple: NAME=VALUE
DEV_MFR=Adafruit
DEV_NAME=MCP2221A Breakout
DEV_PN=4471
DEV_VER=
DEV_TAG=Adafruit_MCP2221A_Breakout_4471
